Update to django 1.8 instead of django 1.7
Environment Python 3.4 and Django 1.7

It avoids the exception thrown by: File "/home/dev/dev/sbenv/lib/python3.4/site-packages/debug_toolbar/panels/templates/views.py", line 6, in <module>
    from django.template.engine import Engine
ImportError: No module named 'django.template.engine'